"""empty message

Revision ID: 17e949380004
Revises: f3eb9fd5df59
Create Date: 2023-06-19 13:55:54.505867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e949380004'
down_revision = 'f3eb9fd5df59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zip_code')
        batch_op.drop_column('location')
        batch_op.drop_column('city')
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('helper', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
