"""empty message

Revision ID: 3b50936a0803
Revises: 2b59b6fb6524
Create Date: 2023-06-02 17:11:58.897395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b50936a0803'
down_revision = '2b59b6fb6524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, foreign_key=True),
    sa.Column('bio', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=True, foreign_key=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True, foreign_key=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('date', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=True, foreign_key=True),
    sa.Column('post_id', sa.Integer(), nullable=True, foreign_key=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['profile_image'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('name')
        batch_op.drop_column('profile_image')

    op.drop_table('post_candidate')
    op.drop_table('post')
    op.drop_table('image')
    op.drop_table('helper')
    # ### end Alembic commands ###
