"""empty message

Revision ID: 66adb8d56c3e
Revises: 7188333c49ee
Create Date: 2023-06-19 22:56:37.170574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66adb8d56c3e'
down_revision = '7188333c49ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
