"""empty message

Revision ID: df1c72622110
Revises: 17e949380004
Create Date: 2023-06-19 15:50:14.112418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1c72622110'
down_revision = '17e949380004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=256), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('city')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
